name: twaddle-backend CI

on:
  push:
    branches: [ "main" ]

env:
  IMAGE_NAME: twaddle-backend

jobs:
  build:
    name: Build and Push
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Dockr.it
        uses: docker/login-action@v2
        with:
          registry: dockr.it
          username: ${{ secrets.DOCKR_USER }}
          password: ${{ secrets.DOCKR_PASS }}

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: | 
            dockr.it/${{ env.IMAGE_NAME }}:latest
            dockr.it/${{ env.IMAGE_NAME }}:${{ github.sha }}
            ghcr.io/stenstromen/${{ env.IMAGE_NAME }}:latest
            ghcr.io/stenstromen/${{ env.IMAGE_NAME }}:${{ github.sha }}
          cache-from: type=gha
          cache-to: type=gha,mode=max